//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PfWebConsultaNovedadEnvioMailService
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://service.pfwebconsultanovedadenviomail.ecobis.cobiscorp.ws/", ConfigurationName = "PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMail")]
    public interface PfWebConsultaNovedadEnvioMail
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://service.pfwebconsultanovedadenviomail.ecobis.cobiscorp.ws/PfWebConsultaNov" +
            "edadEnvioMail/PfWebConsultaNovedadEnvioMail", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CTSServiceResponseTO))]
        System.Threading.Tasks.Task<PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMailResponse> PfWebConsultaNovedadEnvioMailAsync(PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMailRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://dto2.commons.ecobis.cobiscorp")]
    public partial class RequestConnection
    {

        private string userField;

        private string passwordField;

        private string applicationIDField;

        private string sessionIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string applicationID
        {
            get
            {
                return this.applicationIDField;
            }
            set
            {
                this.applicationIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string sessionID
        {
            get
            {
                return this.sessionIDField;
            }
            set
            {
                this.sessionIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://dto.pfwebconsultanovedadenviomail.ecobis.cobiscorp")]
    public partial class PfWebConsultaNovedadEnvioMailRet
    {

        private int onSolicitudField;

        private bool onSolicitudFieldSpecified;

        private string oeSolicitudField;

        private string onIdDebinField;

        private string onCuilField;

        private int onEnteField;

        private bool onEnteFieldSpecified;

        private string odEmailField;

        private string onCbuField;

        private string ocTipoDocumentoField;

        private string onDocumentoField;

        private string odNombreField;

        private string odApellidoField;

        private string onTelefonoField;

        private string odTipoPlazoFijoField;

        private decimal oiCapitalPlazoFijoField;

        private bool oiCapitalPlazoFijoFieldSpecified;

        private int okPlazoField;

        private bool okPlazoFieldSpecified;

        private double opTasaSolicitudField;

        private bool opTasaSolicitudFieldSpecified;

        private double opTasaParamPfField;

        private bool opTasaParamPfFieldSpecified;

        private string onCertificadoField;

        private decimal oiInteresEstimadoPfField;

        private bool oiInteresEstimadoPfFieldSpecified;

        private string ofAltaSolicitudField;

        private string ofAprobacionDebinField;

        private string ofAltaPlazoFijoField;

        private string ofVencimientoPlazoFijoField;

        private string ofCancelacionPlazoFijoField;

        private string ofEnvioMailField;

        private string ofRechazoTrasferenciaField;

        private string ofTransferenciaRealizadaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int onSolicitud
        {
            get
            {
                return this.onSolicitudField;
            }
            set
            {
                this.onSolicitudField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onSolicitudSpecified
        {
            get
            {
                return this.onSolicitudFieldSpecified;
            }
            set
            {
                this.onSolicitudFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string oeSolicitud
        {
            get
            {
                return this.oeSolicitudField;
            }
            set
            {
                this.oeSolicitudField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string onIdDebin
        {
            get
            {
                return this.onIdDebinField;
            }
            set
            {
                this.onIdDebinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string onCuil
        {
            get
            {
                return this.onCuilField;
            }
            set
            {
                this.onCuilField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public int onEnte
        {
            get
            {
                return this.onEnteField;
            }
            set
            {
                this.onEnteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onEnteSpecified
        {
            get
            {
                return this.onEnteFieldSpecified;
            }
            set
            {
                this.onEnteFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string odEmail
        {
            get
            {
                return this.odEmailField;
            }
            set
            {
                this.odEmailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string onCbu
        {
            get
            {
                return this.onCbuField;
            }
            set
            {
                this.onCbuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string ocTipoDocumento
        {
            get
            {
                return this.ocTipoDocumentoField;
            }
            set
            {
                this.ocTipoDocumentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string onDocumento
        {
            get
            {
                return this.onDocumentoField;
            }
            set
            {
                this.onDocumentoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string odNombre
        {
            get
            {
                return this.odNombreField;
            }
            set
            {
                this.odNombreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string odApellido
        {
            get
            {
                return this.odApellidoField;
            }
            set
            {
                this.odApellidoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string onTelefono
        {
            get
            {
                return this.onTelefonoField;
            }
            set
            {
                this.onTelefonoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string odTipoPlazoFijo
        {
            get
            {
                return this.odTipoPlazoFijoField;
            }
            set
            {
                this.odTipoPlazoFijoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public decimal oiCapitalPlazoFijo
        {
            get
            {
                return this.oiCapitalPlazoFijoField;
            }
            set
            {
                this.oiCapitalPlazoFijoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oiCapitalPlazoFijoSpecified
        {
            get
            {
                return this.oiCapitalPlazoFijoFieldSpecified;
            }
            set
            {
                this.oiCapitalPlazoFijoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public int okPlazo
        {
            get
            {
                return this.okPlazoField;
            }
            set
            {
                this.okPlazoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool okPlazoSpecified
        {
            get
            {
                return this.okPlazoFieldSpecified;
            }
            set
            {
                this.okPlazoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public double opTasaSolicitud
        {
            get
            {
                return this.opTasaSolicitudField;
            }
            set
            {
                this.opTasaSolicitudField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opTasaSolicitudSpecified
        {
            get
            {
                return this.opTasaSolicitudFieldSpecified;
            }
            set
            {
                this.opTasaSolicitudFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public double opTasaParamPf
        {
            get
            {
                return this.opTasaParamPfField;
            }
            set
            {
                this.opTasaParamPfField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool opTasaParamPfSpecified
        {
            get
            {
                return this.opTasaParamPfFieldSpecified;
            }
            set
            {
                this.opTasaParamPfFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public string onCertificado
        {
            get
            {
                return this.onCertificadoField;
            }
            set
            {
                this.onCertificadoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public decimal oiInteresEstimadoPf
        {
            get
            {
                return this.oiInteresEstimadoPfField;
            }
            set
            {
                this.oiInteresEstimadoPfField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oiInteresEstimadoPfSpecified
        {
            get
            {
                return this.oiInteresEstimadoPfFieldSpecified;
            }
            set
            {
                this.oiInteresEstimadoPfFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
        public string ofAltaSolicitud
        {
            get
            {
                return this.ofAltaSolicitudField;
            }
            set
            {
                this.ofAltaSolicitudField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public string ofAprobacionDebin
        {
            get
            {
                return this.ofAprobacionDebinField;
            }
            set
            {
                this.ofAprobacionDebinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public string ofAltaPlazoFijo
        {
            get
            {
                return this.ofAltaPlazoFijoField;
            }
            set
            {
                this.ofAltaPlazoFijoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 22)]
        public string ofVencimientoPlazoFijo
        {
            get
            {
                return this.ofVencimientoPlazoFijoField;
            }
            set
            {
                this.ofVencimientoPlazoFijoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 23)]
        public string ofCancelacionPlazoFijo
        {
            get
            {
                return this.ofCancelacionPlazoFijoField;
            }
            set
            {
                this.ofCancelacionPlazoFijoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 24)]
        public string ofEnvioMail
        {
            get
            {
                return this.ofEnvioMailField;
            }
            set
            {
                this.ofEnvioMailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 25)]
        public string ofRechazoTrasferencia
        {
            get
            {
                return this.ofRechazoTrasferenciaField;
            }
            set
            {
                this.ofRechazoTrasferenciaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 26)]
        public string ofTransferenciaRealizada
        {
            get
            {
                return this.ofTransferenciaRealizadaField;
            }
            set
            {
                this.ofTransferenciaRealizadaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://dto2.commons.ecobis.cobiscorp")]
    public partial class ServiceError
    {

        private string codeField;

        private string messageField;

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://dto2.commons.ecobis.cobiscorp")]
    public partial class MessageTO
    {

        private string codeField;

        private string messageField;

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PfWebConsultaNovedadEnvioMailRes))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://dto2.sdf.cts.cobis.cobiscorp.com")]
    public partial class CTSServiceResponseTO
    {

        private bool successField;

        private bool successFieldSpecified;

        private MessageTO[] messagesField;

        private ServiceError[] serviceErrorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool successSpecified
        {
            get
            {
                return this.successFieldSpecified;
            }
            set
            {
                this.successFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messages", IsNullable = true, Order = 1)]
        public MessageTO[] messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceError", IsNullable = true, Order = 2)]
        public ServiceError[] serviceError
        {
            get
            {
                return this.serviceErrorField;
            }
            set
            {
                this.serviceErrorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://dto.pfwebconsultanovedadenviomail.ecobis.cobiscorp")]
    public partial class PfWebConsultaNovedadEnvioMailRes : CTSServiceResponseTO
    {

        private PfWebConsultaNovedadEnvioMailRet[] pfWebConsultaNovedadEnvioMailRetField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pfWebConsultaNovedadEnvioMailRet", IsNullable = true, Order = 0)]
        public PfWebConsultaNovedadEnvioMailRet[] pfWebConsultaNovedadEnvioMailRet
        {
            get
            {
                return this.pfWebConsultaNovedadEnvioMailRetField;
            }
            set
            {
                this.pfWebConsultaNovedadEnvioMailRetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://dto.pfwebconsultanovedadenviomail.ecobis.cobiscorp")]
    public partial class PfWebConsultaNovedadEnvioMailFil
    {

        private int isSiguienteField;

        private bool isSiguienteFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int isSiguiente
        {
            get
            {
                return this.isSiguienteField;
            }
            set
            {
                this.isSiguienteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isSiguienteSpecified
        {
            get
            {
                return this.isSiguienteFieldSpecified;
            }
            set
            {
                this.isSiguienteFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.pfwebconsultanovedadenviomail.ecobis.cobiscorp")]
    public partial class Fil
    {

        private PfWebConsultaNovedadEnvioMailFil inPfWebConsultaNovedadEnvioMailFilField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public PfWebConsultaNovedadEnvioMailFil inPfWebConsultaNovedadEnvioMailFil
        {
            get
            {
                return this.inPfWebConsultaNovedadEnvioMailFilField;
            }
            set
            {
                this.inPfWebConsultaNovedadEnvioMailFilField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "PfWebConsultaNovedadEnvioMail", WrapperNamespace = "http://service.pfwebconsultanovedadenviomail.ecobis.cobiscorp", IsWrapped = true)]
    public partial class PfWebConsultaNovedadEnvioMailRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.pfwebconsultanovedadenviomail.ecobis.cobiscorp", Order = 0)]
        public PfWebConsultaNovedadEnvioMailService.RequestConnection requestConnection;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.pfwebconsultanovedadenviomail.ecobis.cobiscorp", Order = 1)]
        public PfWebConsultaNovedadEnvioMailService.Fil fil;

        public PfWebConsultaNovedadEnvioMailRequest()
        {
        }

        public PfWebConsultaNovedadEnvioMailRequest(PfWebConsultaNovedadEnvioMailService.RequestConnection requestConnection, PfWebConsultaNovedadEnvioMailService.Fil fil)
        {
            this.requestConnection = requestConnection;
            this.fil = fil;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "PfWebConsultaNovedadEnvioMailResponse", WrapperNamespace = "http://service.pfwebconsultanovedadenviomail.ecobis.cobiscorp", IsWrapped = true)]
    public partial class PfWebConsultaNovedadEnvioMailResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.pfwebconsultanovedadenviomail.ecobis.cobiscorp", Order = 0)]
        public PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMailRes executeResponse;

        public PfWebConsultaNovedadEnvioMailResponse()
        {
        }

        public PfWebConsultaNovedadEnvioMailResponse(PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMailRes executeResponse)
        {
            this.executeResponse = executeResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public interface PfWebConsultaNovedadEnvioMailChannel : PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMail, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public partial class PfWebConsultaNovedadEnvioMailClient : System.ServiceModel.ClientBase<PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMail>, PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMail
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public PfWebConsultaNovedadEnvioMailClient() :
                base(PfWebConsultaNovedadEnvioMailClient.GetDefaultBinding(), PfWebConsultaNovedadEnvioMailClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PfWebConsultaNovedadEnvioMailWSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PfWebConsultaNovedadEnvioMailClient(EndpointConfiguration endpointConfiguration) :
                base(PfWebConsultaNovedadEnvioMailClient.GetBindingForEndpoint(endpointConfiguration), PfWebConsultaNovedadEnvioMailClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PfWebConsultaNovedadEnvioMailClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(PfWebConsultaNovedadEnvioMailClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PfWebConsultaNovedadEnvioMailClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(PfWebConsultaNovedadEnvioMailClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PfWebConsultaNovedadEnvioMailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMailResponse> PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMail.PfWebConsultaNovedadEnvioMailAsync(PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMailRequest request)
        {
            return base.Channel.PfWebConsultaNovedadEnvioMailAsync(request);
        }

        public System.Threading.Tasks.Task<PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMailResponse> PfWebConsultaNovedadEnvioMailAsync(PfWebConsultaNovedadEnvioMailService.RequestConnection requestConnection, PfWebConsultaNovedadEnvioMailService.Fil fil)
        {
            PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMailRequest inValue = new PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMailRequest()
            {
                requestConnection = requestConnection,
                fil = fil
            };

            return ((PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMail)(this)).PfWebConsultaNovedadEnvioMailAsync(inValue);
        }

        public System.Threading.Tasks.Task<PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMailResponse> PfWebConsultaNovedadEnvioMailAsync(PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMailRequest request)
        {
            PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMailRequest inValue = request;

            return ((PfWebConsultaNovedadEnvioMailService.PfWebConsultaNovedadEnvioMail)(this)).PfWebConsultaNovedadEnvioMailAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PfWebConsultaNovedadEnvioMailWSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PfWebConsultaNovedadEnvioMailWSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://172.28.195.215:9080/COBISCorp.eCOBIS.PfWebConsultaNovedadEnvioMail.Service" +
                        "/PfWebConsultaNovedadEnvioMailWSService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PfWebConsultaNovedadEnvioMailClient.GetBindingForEndpoint(EndpointConfiguration.PfWebConsultaNovedadEnvioMailWSPort);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PfWebConsultaNovedadEnvioMailClient.GetEndpointAddress(EndpointConfiguration.PfWebConsultaNovedadEnvioMailWSPort);
        }

        public enum EndpointConfiguration
        {

            PfWebConsultaNovedadEnvioMailWSPort,
        }
    }
}
